Document: gimp
Title: Debian gimp Manual
Author: <insert document author here>
Abstract: This manual describes what gimp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gimp/gimp.sgml.gz

Format: postscript
Files: /usr/share/doc/gimp/gimp.ps.gz

Format: text
Files: /usr/share/doc/gimp/gimp.text.gz

Format: HTML
Index: /usr/share/doc/gimp/html/index.html
Files: /usr/share/doc/gimp/html/*.html
